// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Chromy",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Chromy",
            targets: ["AppModule"],
            bundleIdentifier: "asdf.ColorHunt",
            teamIdentifier: "M9H5XU96C6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Color Hunt uses the camera to capture real-world colours for crystal spells."),
                .photoLibrary(purposeString: "Color Hunt lets you choose gallery photos for spell memories."),
                .photoLibraryAdd(purposeString: "Color Hunt saves spell book colour cards to your gallery.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.version("6")]
)
